import { Box, Button, TextField, Typography } from '@mui/material'
import React, { useRef, useState } from 'react'

// DO NOT EDIT THIS FILE
const Password = ({setStep}) => {
  // THIS useRef IS A HOOK THAT USED IN UNCONTROLL FORM, YOU DON'T NEED TO WORRY ABOUT THIS.
  const inputRef = useRef()
  const [errorMessage,setErrorMessage] = useState("")
  const submitPassword = (e)=>{
    e.preventDefault()
  // GET THE INPUT VALUE OF THE FORM FORM
    if(inputRef.current.value === "2513022"){
        // THIS IS A CHECK FOR THE VARIABLE CALLED setStep
        if(!setStep){
            setErrorMessage("hint : You entered the correct password, but it look like there's something wrong in your function please check the props")
        }else{
        // IF THERE IS A VARIABLE setStep, IT WILL CHANGE TO THE NEXT STEP
            setStep(1)
        }
    // THIS IS A CASE THAT THE PASSWORD IS INCORRECT
    }else{
        setErrorMessage("Incorrect password !, The password is 2513022")
    }
  }
  return (
    // WHEN THE FORM IS SUBMITTED (BUTTON CLICKED) THE ONSUBMIT WILL FIRE submitPassword FUNCTION.
    <Box display={"flex"} flexDirection="column" gap={5} component="form" onSubmit={submitPassword} >
        <Typography  variant='h2' >Please, enter the password</Typography>
        <TextField inputRef={inputRef} size='medium' label="Password is 2513022" variant="outlined" error={!!errorMessage} />
        {errorMessage && <Typography color={"red"}>{errorMessage}</Typography>}
        <Button type='submit' variant='contained' size='large' color='primary'>Submit password</Button>
    </Box>
  )
}

export default Password